# my_tuple = (1,2,3,4)
# print(my_tuple)
# print(my_tuple[2])
# print(my_tuple[0:3])
# # my_tuple[1] = 6
# # print(my_tuple)
# print(len(my_tuple))
# del my_tuple
# my_tuple2 = (1,2,4,6,5)
# print(max(my_tuple2))
# print(min(my_tuple2))
# print(sum(my_tuple2))
# print(sum(my_tuple2)/len(my_tuple2))
# print(my_tuple2.index(4))
# print(my_tuple2.count(4))
tuple2 = ("Wes,John,Ivy,Grace")
print(tuple2)
print(tuple2[2])
print(len(tuple2))
print(tuple2.index("Ivy"))
print(tuple2.count("John"))
print(tuple2[0:2])
